-- -- -
-- RESET Veterinaria
-- -- --
USE lil_pets;

-- DESACTIVAR LOS FK
SET FOREIGN_KEY_CHECKS=0;

TRUNCATE TABLE CATEGORIA_EMPLEADO;
TRUNCATE TABLE CATEGORIA_PRODUCTO;
TRUNCATE TABLE CLIENTE;
TRUNCATE TABLE DETALLE_VENTA;
TRUNCATE TABLE EMPLEADO;
TRUNCATE TABLE HISTORIAL;
TRUNCATE TABLE LOG_DETALLE_VENTA;
TRUNCATE TABLE LOG_PRECIO_ANTIGUO;
TRUNCATE TABLE LOG_SERVICIO_SOLICITADOS;
TRUNCATE TABLE MASCOTA;
TRUNCATE TABLE PEDIDO;
TRUNCATE TABLE PRODUCTO;
TRUNCATE TABLE PROVEEDOR;
TRUNCATE TABLE SERVICIO;
TRUNCATE TABLE SERVICIO_SOLICITADO;
TRUNCATE TABLE SUBCATEGORIA_PRODUCTO;

SET FOREIGN_KEY_CHECKS=1;