
/* 
PROYECTO FINAL - VETERINARIA

• Esquema de bases de datos - Veterinaria & PetShop 'Lil Pet's
• Alumno: Julian Alejandro Medina
• Comisión: #3496
• Profesor: Cesar Aracena
• Tutor: Sergio Occhipinti

*/

-- EJERCICIO 1.

-- USO DE LA BD
USE `Lil_Pets`;

-- INICIO DE LA SENTENCIA PARA LA TRANSACCION CONTROLADA (COMMIT / ROLLBACK)

-- SE UTILIZARA LA TABLA "PROVEEDOR" LA CUAL CUENTA CON 2 REGISTROS
SELECT * FROM PROVEEDOR;

-- SE DESACTIVA EL COMMIT AUTOMATICO
SET @@AUTOCOMMIT = 0;

-- INICIO DE LA TRANSACCION CONTROLADA
START TRANSACTION;

-- SE ELIMINARAN LOS DOS REGISTROS QUE CONTIENE LA TABLA PROVEEDOR
DELETE FROM PROVEEDOR WHERE PROV_ID IN (1,2);

-- SE UTILIZA ROLLBACK PARA REVERTIR LAS ELIMINACIONES TEMPORALES
-- ROLLBACK;

-- SE UTILIZA COMMIT PARA EFECTUAR DE FORMA PERMANENTE LAS ELIMINACIONES TEMPORALES
-- COMMIT;


-- SENTENCIA CORRESPONDIENTE A LA TABLA PROVEEDOR QUE CONTIENE LOS REGISTROS ORIGINALES
-- Estructura para insertar registros en `PROVEEDOR`
/*
INSERT INTO `PROVEEDOR`
	VALUES
		(1,'Wuckert LLC','30.927.7183','639-822-6952','dconn0@gov.uk','31306 Bobwhite Way','fotki.com'),
		(2,'Ferry Group','53.130.7404','724-237-5613','mokie1@deviantart.com','7 4th Parkway','lycos.com');
*/


-- EJERCICIO 2.
-- INICIO DE LA SENTENCIA PARA LA TRANSACCION CONTROLADA (SAVEPOINTS)

-- SE UTILIZARA LA TABLA "HISTORIAL" LA CUAL CUENTA CON UN SOLO REGISTRO
SELECT * FROM HISTORIAL;

-- INICIO DE LA TRANSACCION
START TRANSACTION;

-- INSERCION DE NUEVOS REGISTROS
-- CUATRO NUEVOS REGISTROS DE INSERCION
INSERT INTO `HISTORIAL` VALUES (NULL,2,'bajo peso');
INSERT INTO `HISTORIAL` VALUES (NULL,3,'bajo peso');
INSERT INTO `HISTORIAL` VALUES (NULL,4,'bajo peso');
INSERT INTO `HISTORIAL` VALUES (NULL,5,'bajo peso');
-- PRIMER PUNTO DE GUARDADO PARA LOS PRIMEROS CUATRO INSERT
SAVEPOINT primeros_cuatros;

-- CUATRO NUEVOS REGISTROS DE INSERCION
INSERT INTO `HISTORIAL` VALUES (NULL,6,'bajo peso');
INSERT INTO `HISTORIAL` VALUES (NULL,7,'bajo peso');
INSERT INTO `HISTORIAL` VALUES (NULL,8,'bajo peso');
INSERT INTO `HISTORIAL` VALUES (NULL,9,'bajo peso');
-- SEGUNDO PUNTO DE GUARDADO PARA LOS ULTIMOS CUATRO INSERT
SAVEPOINT ultimos_cuatros;

-- REVERTIR LOS INSERT HASTA EL PRIMER SAVEPOINT, DONDE LOS ULTIMOS CUATROS QUEDAN DESAFECTADOS
ROLLBACK TO primeros_cuatros;




 